// <auto-generated />
using System;
using CleanArchitecture.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanArchitecture.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CleanArchitecture.Domain.Entities.DetalleFactura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("FacturaId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Producto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.ToTable("DetallesFactura");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 1,
                            FacturaId = 1,
                            PrecioUnitario = 1200.00m,
                            Producto = "Laptop Dell XPS 15",
                            Subtotal = 1200.00m
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 1,
                            FacturaId = 1,
                            PrecioUnitario = 50.50m,
                            Producto = "Mouse Logitech MX Master",
                            Subtotal = 50.50m
                        },
                        new
                        {
                            Id = 3,
                            Cantidad = 2,
                            FacturaId = 2,
                            PrecioUnitario = 89.99m,
                            Producto = "Teclado Mecánico Keychron K2",
                            Subtotal = 179.98m
                        },
                        new
                        {
                            Id = 4,
                            Cantidad = 1,
                            FacturaId = 2,
                            PrecioUnitario = 450.00m,
                            Producto = "Monitor LG 27 4K",
                            Subtotal = 450.00m
                        },
                        new
                        {
                            Id = 5,
                            Cantidad = 1,
                            FacturaId = 2,
                            PrecioUnitario = 220.77m,
                            Producto = "Webcam Logitech C920",
                            Subtotal = 220.77m
                        },
                        new
                        {
                            Id = 6,
                            Cantidad = 1,
                            FacturaId = 3,
                            PrecioUnitario = 1299.99m,
                            Producto = "iPhone 15 Pro",
                            Subtotal = 1299.99m
                        },
                        new
                        {
                            Id = 7,
                            Cantidad = 2,
                            FacturaId = 3,
                            PrecioUnitario = 249.99m,
                            Producto = "AirPods Pro",
                            Subtotal = 499.98m
                        },
                        new
                        {
                            Id = 8,
                            Cantidad = 1,
                            FacturaId = 3,
                            PrecioUnitario = 45.00m,
                            Producto = "Cargador USB-C 65W",
                            Subtotal = 45.00m
                        },
                        new
                        {
                            Id = 9,
                            Cantidad = 3,
                            FacturaId = 3,
                            PrecioUnitario = 25.00m,
                            Producto = "Cable USB-C a Lightning",
                            Subtotal = 75.00m
                        });
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Entities.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Facturas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = "Pagada",
                            FechaEmision = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroFactura = "FAC-2024-001",
                            Total = 1250.50m,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Estado = "Pendiente",
                            FechaEmision = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroFactura = "FAC-2024-002",
                            Total = 850.75m,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 3,
                            Estado = "Pagada",
                            FechaEmision = new DateTime(2024, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroFactura = "FAC-2024-003",
                            Total = 2100.00m,
                            UsuarioId = 1
                        });
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Email = "juan.perez@email.com",
                            FechaRegistro = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Juan Pérez",
                            Telefono = "+34 612 345 678"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Email = "maria.garcia@email.com",
                            FechaRegistro = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "María García",
                            Telefono = "+34 623 456 789"
                        },
                        new
                        {
                            Id = 3,
                            Activo = false,
                            Email = "carlos.lopez@email.com",
                            FechaRegistro = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Carlos López",
                            Telefono = "+34 634 567 890"
                        });
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Entities.DetalleFactura", b =>
                {
                    b.HasOne("CleanArchitecture.Domain.Entities.Factura", "Factura")
                        .WithMany("DetallesFactura")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Entities.Factura", b =>
                {
                    b.HasOne("CleanArchitecture.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Facturas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Entities.Factura", b =>
                {
                    b.Navigation("DetallesFactura");
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Facturas");
                });
#pragma warning restore 612, 618
        }
    }
}
